/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArcadiaToolbarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  showBold: true,
  showItalic: true,
  showStrikethrough: true,
  showHighlight: true,
  showHeadings: true,
  showLists: true,
  showBlockquote: true,
  showLink: true,
  showCode: true,
  showScripture: true,
  toolbarPosition: "top",
  scriptureTranslation: "ESV"
};
var ArcadiaToolbarPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.toolbarEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.updateToolbar();
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.updateToolbar();
      })
    );
    this.addCommand({
      id: "toggle-bold",
      name: "Toggle Bold",
      editorCallback: (editor) => this.toggleBold(editor)
    });
    this.addCommand({
      id: "toggle-italic",
      name: "Toggle Italic",
      editorCallback: (editor) => this.toggleItalic(editor)
    });
    this.addCommand({
      id: "toggle-strikethrough",
      name: "Toggle Strikethrough",
      editorCallback: (editor) => this.toggleStrikethrough(editor)
    });
    this.addCommand({
      id: "toggle-highlight",
      name: "Toggle Highlight",
      editorCallback: (editor) => this.toggleHighlight(editor)
    });
    this.addCommand({
      id: "insert-heading-1",
      name: "Insert Heading 1",
      editorCallback: (editor) => this.insertHeading(editor, 1)
    });
    this.addCommand({
      id: "insert-heading-2",
      name: "Insert Heading 2",
      editorCallback: (editor) => this.insertHeading(editor, 2)
    });
    this.addCommand({
      id: "insert-heading-3",
      name: "Insert Heading 3",
      editorCallback: (editor) => this.insertHeading(editor, 3)
    });
    this.addCommand({
      id: "toggle-bullet-list",
      name: "Toggle Bullet List",
      editorCallback: (editor) => this.toggleBulletList(editor)
    });
    this.addCommand({
      id: "toggle-numbered-list",
      name: "Toggle Numbered List",
      editorCallback: (editor) => this.toggleNumberedList(editor)
    });
    this.addCommand({
      id: "toggle-blockquote",
      name: "Toggle Blockquote",
      editorCallback: (editor) => this.toggleBlockquote(editor)
    });
    this.addCommand({
      id: "insert-link",
      name: "Insert Link",
      editorCallback: (editor) => this.insertLink(editor)
    });
    this.addCommand({
      id: "toggle-inline-code",
      name: "Toggle Inline Code",
      editorCallback: (editor) => this.toggleInlineCode(editor)
    });
    this.addCommand({
      id: "insert-code-block",
      name: "Insert Code Block",
      editorCallback: (editor) => this.insertCodeBlock(editor)
    });
    this.addCommand({
      id: "insert-scripture-block",
      name: "Insert Scripture Block",
      editorCallback: (editor) => this.insertScriptureBlock(editor)
    });
    this.addSettingTab(new ArcadiaToolbarSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.updateToolbar();
    });
  }
  onunload() {
    this.removeToolbar();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateToolbar();
  }
  removeToolbar() {
    if (this.toolbarEl) {
      this.toolbarEl.remove();
      this.toolbarEl = null;
    }
  }
  updateToolbar() {
    this.removeToolbar();
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView)
      return;
    const editorEl = activeView.containerEl.querySelector(".cm-editor");
    if (!editorEl)
      return;
    this.toolbarEl = document.createElement("div");
    this.toolbarEl.className = "arcadia-toolbar";
    const buttons = [
      {
        id: "bold",
        icon: "bold",
        tooltip: "Bold (Ctrl/Cmd+B)",
        action: (editor) => this.toggleBold(editor),
        settingKey: "showBold"
      },
      {
        id: "italic",
        icon: "italic",
        tooltip: "Italic (Ctrl/Cmd+I)",
        action: (editor) => this.toggleItalic(editor),
        settingKey: "showItalic"
      },
      {
        id: "strikethrough",
        icon: "strikethrough",
        tooltip: "Strikethrough",
        action: (editor) => this.toggleStrikethrough(editor),
        settingKey: "showStrikethrough"
      },
      {
        id: "highlight",
        icon: "highlighter",
        tooltip: "Highlight",
        action: (editor) => this.toggleHighlight(editor),
        settingKey: "showHighlight"
      },
      { id: "separator-1", icon: "", tooltip: "", action: () => {
      } },
      {
        id: "heading-1",
        icon: "heading-1",
        tooltip: "Heading 1",
        action: (editor) => this.insertHeading(editor, 1),
        settingKey: "showHeadings"
      },
      {
        id: "heading-2",
        icon: "heading-2",
        tooltip: "Heading 2",
        action: (editor) => this.insertHeading(editor, 2),
        settingKey: "showHeadings"
      },
      {
        id: "heading-3",
        icon: "heading-3",
        tooltip: "Heading 3",
        action: (editor) => this.insertHeading(editor, 3),
        settingKey: "showHeadings"
      },
      { id: "separator-2", icon: "", tooltip: "", action: () => {
      } },
      {
        id: "bullet-list",
        icon: "list",
        tooltip: "Bullet List",
        action: (editor) => this.toggleBulletList(editor),
        settingKey: "showLists"
      },
      {
        id: "numbered-list",
        icon: "list-ordered",
        tooltip: "Numbered List",
        action: (editor) => this.toggleNumberedList(editor),
        settingKey: "showLists"
      },
      {
        id: "blockquote",
        icon: "quote",
        tooltip: "Blockquote",
        action: (editor) => this.toggleBlockquote(editor),
        settingKey: "showBlockquote"
      },
      { id: "separator-3", icon: "", tooltip: "", action: () => {
      } },
      {
        id: "link",
        icon: "link",
        tooltip: "Insert Link",
        action: (editor) => this.insertLink(editor),
        settingKey: "showLink"
      },
      {
        id: "inline-code",
        icon: "code",
        tooltip: "Inline Code",
        action: (editor) => this.toggleInlineCode(editor),
        settingKey: "showCode"
      },
      {
        id: "code-block",
        icon: "file-code",
        tooltip: "Code Block",
        action: (editor) => this.insertCodeBlock(editor),
        settingKey: "showCode"
      },
      { id: "separator-4", icon: "", tooltip: "", action: () => {
      } },
      {
        id: "scripture",
        icon: "book-open",
        tooltip: "Insert Scripture Block",
        action: (editor) => this.insertScriptureBlock(editor),
        settingKey: "showScripture"
      }
    ];
    for (const btn of buttons) {
      if (btn.id.startsWith("separator")) {
        const separator = document.createElement("div");
        separator.className = "arcadia-toolbar-separator";
        this.toolbarEl.appendChild(separator);
        continue;
      }
      if (btn.settingKey && !this.settings[btn.settingKey]) {
        continue;
      }
      const buttonEl = document.createElement("button");
      buttonEl.className = "arcadia-toolbar-button";
      buttonEl.setAttribute("aria-label", btn.tooltip);
      buttonEl.setAttribute("title", btn.tooltip);
      (0, import_obsidian.setIcon)(buttonEl, btn.icon);
      buttonEl.addEventListener("click", (e) => {
        e.preventDefault();
        const editor = activeView.editor;
        if (editor) {
          btn.action(editor);
        }
      });
      this.toolbarEl.appendChild(buttonEl);
    }
    const cmScroller = editorEl.querySelector(".cm-scroller");
    if (cmScroller && this.settings.toolbarPosition === "top") {
      editorEl.insertBefore(this.toolbarEl, cmScroller);
    } else if (cmScroller) {
      editorEl.appendChild(this.toolbarEl);
    }
  }
  // === Formatting Functions ===
  toggleBold(editor) {
    const selection = editor.getSelection();
    if (selection) {
      if (selection.startsWith("**") && selection.endsWith("**")) {
        editor.replaceSelection(selection.slice(2, -2));
      } else {
        editor.replaceSelection(`**${selection}**`);
      }
    } else {
      const cursor = editor.getCursor();
      editor.replaceRange("****", cursor);
      editor.setCursor({ line: cursor.line, ch: cursor.ch + 2 });
    }
  }
  toggleItalic(editor) {
    const selection = editor.getSelection();
    if (selection) {
      if (selection.startsWith("*") && selection.endsWith("*") && !selection.startsWith("**")) {
        editor.replaceSelection(selection.slice(1, -1));
      } else {
        editor.replaceSelection(`*${selection}*`);
      }
    } else {
      const cursor = editor.getCursor();
      editor.replaceRange("**", cursor);
      editor.setCursor({ line: cursor.line, ch: cursor.ch + 1 });
    }
  }
  toggleStrikethrough(editor) {
    const selection = editor.getSelection();
    if (selection) {
      if (selection.startsWith("~~") && selection.endsWith("~~")) {
        editor.replaceSelection(selection.slice(2, -2));
      } else {
        editor.replaceSelection(`~~${selection}~~`);
      }
    } else {
      const cursor = editor.getCursor();
      editor.replaceRange("~~~~", cursor);
      editor.setCursor({ line: cursor.line, ch: cursor.ch + 2 });
    }
  }
  toggleHighlight(editor) {
    const selection = editor.getSelection();
    if (selection) {
      if (selection.startsWith("==") && selection.endsWith("==")) {
        editor.replaceSelection(selection.slice(2, -2));
      } else {
        editor.replaceSelection(`==${selection}==`);
      }
    } else {
      const cursor = editor.getCursor();
      editor.replaceRange("====", cursor);
      editor.setCursor({ line: cursor.line, ch: cursor.ch + 2 });
    }
  }
  insertHeading(editor, level) {
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const headingPrefix = "#".repeat(level) + " ";
    const headingMatch = line.match(/^(#{1,6})\s/);
    if (headingMatch) {
      const newLine = headingPrefix + line.slice(headingMatch[0].length);
      editor.setLine(cursor.line, newLine);
    } else {
      editor.setLine(cursor.line, headingPrefix + line);
    }
  }
  toggleBulletList(editor) {
    var _a;
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    if (line.match(/^(\s*)- /)) {
      editor.setLine(cursor.line, line.replace(/^(\s*)- /, "$1"));
    } else if (line.match(/^(\s*)\d+\. /)) {
      editor.setLine(cursor.line, line.replace(/^(\s*)\d+\. /, "$1- "));
    } else {
      const indent = ((_a = line.match(/^(\s*)/)) == null ? void 0 : _a[0]) || "";
      editor.setLine(cursor.line, indent + "- " + line.trimStart());
    }
  }
  toggleNumberedList(editor) {
    var _a;
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    if (line.match(/^(\s*)\d+\. /)) {
      editor.setLine(cursor.line, line.replace(/^(\s*)\d+\. /, "$1"));
    } else if (line.match(/^(\s*)- /)) {
      editor.setLine(cursor.line, line.replace(/^(\s*)- /, "$11. "));
    } else {
      const indent = ((_a = line.match(/^(\s*)/)) == null ? void 0 : _a[0]) || "";
      editor.setLine(cursor.line, indent + "1. " + line.trimStart());
    }
  }
  toggleBlockquote(editor) {
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    if (line.startsWith("> ")) {
      editor.setLine(cursor.line, line.slice(2));
    } else {
      editor.setLine(cursor.line, "> " + line);
    }
  }
  insertLink(editor) {
    const selection = editor.getSelection();
    if (selection) {
      editor.replaceSelection(`[${selection}](url)`);
      const cursor = editor.getCursor();
      editor.setSelection(
        { line: cursor.line, ch: cursor.ch - 4 },
        { line: cursor.line, ch: cursor.ch - 1 }
      );
    } else {
      const cursor = editor.getCursor();
      editor.replaceRange("[](url)", cursor);
      editor.setCursor({ line: cursor.line, ch: cursor.ch + 1 });
    }
  }
  toggleInlineCode(editor) {
    const selection = editor.getSelection();
    if (selection) {
      if (selection.startsWith("`") && selection.endsWith("`")) {
        editor.replaceSelection(selection.slice(1, -1));
      } else {
        editor.replaceSelection(`\`${selection}\``);
      }
    } else {
      const cursor = editor.getCursor();
      editor.replaceRange("``", cursor);
      editor.setCursor({ line: cursor.line, ch: cursor.ch + 1 });
    }
  }
  insertCodeBlock(editor) {
    const selection = editor.getSelection();
    const cursor = editor.getCursor();
    if (selection) {
      editor.replaceSelection(`\`\`\`
${selection}
\`\`\``);
    } else {
      editor.replaceRange("```\n\n```", cursor);
      editor.setCursor({ line: cursor.line + 1, ch: 0 });
    }
  }
  insertScriptureBlock(editor) {
    const cursor = editor.getCursor();
    const translation = this.settings.scriptureTranslation;
    const scriptureBlock = `> [!scripture] Scripture Reference
> **Book Chapter:Verse (${translation})**
>
> Enter scripture text here...
`;
    editor.replaceRange(scriptureBlock, cursor);
    editor.setCursor({ line: cursor.line + 1, ch: 3 });
  }
};
var ArcadiaToolbarSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Arcadia Toolbar Settings" });
    new import_obsidian.Setting(containerEl).setName("Toolbar position").setDesc("Where to display the formatting toolbar").addDropdown((dropdown) => dropdown.addOption("top", "Top of editor").addOption("bottom", "Bottom of editor").setValue(this.plugin.settings.toolbarPosition).onChange(async (value) => {
      this.plugin.settings.toolbarPosition = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Toolbar Buttons" });
    new import_obsidian.Setting(containerEl).setName("Show Bold button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showBold).onChange(async (value) => {
      this.plugin.settings.showBold = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Italic button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showItalic).onChange(async (value) => {
      this.plugin.settings.showItalic = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Strikethrough button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showStrikethrough).onChange(async (value) => {
      this.plugin.settings.showStrikethrough = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Highlight button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showHighlight).onChange(async (value) => {
      this.plugin.settings.showHighlight = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Heading buttons").addToggle((toggle) => toggle.setValue(this.plugin.settings.showHeadings).onChange(async (value) => {
      this.plugin.settings.showHeadings = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show List buttons").addToggle((toggle) => toggle.setValue(this.plugin.settings.showLists).onChange(async (value) => {
      this.plugin.settings.showLists = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Blockquote button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showBlockquote).onChange(async (value) => {
      this.plugin.settings.showBlockquote = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Link button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showLink).onChange(async (value) => {
      this.plugin.settings.showLink = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Code buttons").addToggle((toggle) => toggle.setValue(this.plugin.settings.showCode).onChange(async (value) => {
      this.plugin.settings.showCode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Scripture button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showScripture).onChange(async (value) => {
      this.plugin.settings.showScripture = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Scripture Settings" });
    new import_obsidian.Setting(containerEl).setName("Default translation").setDesc("Default Bible translation for scripture blocks").addDropdown((dropdown) => dropdown.addOption("ESV", "ESV - English Standard Version").addOption("NIV", "NIV - New International Version").addOption("KJV", "KJV - King James Version").addOption("NASB", "NASB - New American Standard Bible").addOption("NLT", "NLT - New Living Translation").addOption("CSB", "CSB - Christian Standard Bible").addOption("NKJV", "NKJV - New King James Version").addOption("RSV", "RSV - Revised Standard Version").setValue(this.plugin.settings.scriptureTranslation).onChange(async (value) => {
      this.plugin.settings.scriptureTranslation = value;
      await this.plugin.saveSettings();
    }));
  }
};
