/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArcadiaAuthorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  // Feature Flags
  enableComments: true,
  enableTrackChanges: false,
  enableWordCount: true,
  enableAutoNumbering: false,
  enableTOC: false,
  // Comments Settings
  defaultAuthor: "Author",
  showResolvedComments: false,
  commentHighlightColor: "#fef08a",
  // Word Count Settings
  showWordCount: true,
  showCharacterCount: true,
  showReadingTime: true,
  wordsPerMinute: 200,
  wordCountPosition: "statusbar",
  // Track Changes Settings
  trackChangesAuthor: "Author",
  showInsertions: true,
  showDeletions: true
};
var ArcadiaAuthorPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItem = null;
    this.authorToolbarEl = null;
    this.commentsPanelEl = null;
    this.currentAnnotations = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    if (this.settings.enableWordCount && this.settings.wordCountPosition === "statusbar") {
      this.statusBarItem = this.addStatusBarItem();
      this.statusBarItem.addClass("arcadia-word-count");
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        this.onActiveLeafChange(leaf);
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-change", (0, import_obsidian.debounce)((editor) => {
        this.updateWordCount(editor);
      }, 300, true))
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.updateAuthorToolbar();
      })
    );
    this.registerCommands();
    this.addSettingTab(new ArcadiaAuthorSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.updateAuthorToolbar();
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView == null ? void 0 : activeView.editor) {
        this.updateWordCount(activeView.editor);
      }
    });
  }
  onunload() {
    this.removeAuthorToolbar();
    if (this.commentsPanelEl) {
      this.commentsPanelEl.remove();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ============================================================================
  // COMMANDS REGISTRATION
  // ============================================================================
  registerCommands() {
    if (this.settings.enableComments) {
      this.addCommand({
        id: "add-comment",
        name: "Add Comment",
        icon: "message-square-plus",
        editorCallback: (editor, view) => {
          this.addComment(editor, view);
        }
      });
      this.addCommand({
        id: "toggle-comments-panel",
        name: "Toggle Comments Panel",
        icon: "message-square",
        callback: () => {
          this.toggleCommentsPanel();
        }
      });
      this.addCommand({
        id: "resolve-all-comments",
        name: "Resolve All Comments",
        icon: "check-check",
        callback: () => {
          this.resolveAllComments();
        }
      });
    }
    this.addCommand({
      id: "show-document-statistics",
      name: "Show Document Statistics",
      icon: "bar-chart-2",
      callback: () => {
        this.showDocumentStatistics();
      }
    });
    this.addCommand({
      id: "export-clean-markdown",
      name: "Export Clean Markdown (without annotations)",
      icon: "file-text",
      callback: () => {
        this.exportCleanMarkdown();
      }
    });
  }
  // ============================================================================
  // EVENT HANDLERS
  // ============================================================================
  onActiveLeafChange(leaf) {
    this.updateAuthorToolbar();
    if (leaf) {
      const view = leaf.view;
      if (view instanceof import_obsidian.MarkdownView) {
        this.loadAnnotationsForFile(view.file);
        this.updateWordCount(view.editor);
      }
    }
  }
  // ============================================================================
  // AUTHOR TOOLBAR (docked below Arcadia Toolbar)
  // ============================================================================
  removeAuthorToolbar() {
    if (this.authorToolbarEl) {
      this.authorToolbarEl.remove();
      this.authorToolbarEl = null;
    }
  }
  updateAuthorToolbar() {
    this.removeAuthorToolbar();
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView)
      return;
    const editorEl = activeView.containerEl.querySelector(".cm-editor");
    if (!editorEl)
      return;
    this.authorToolbarEl = createEl("div", { cls: "arcadia-author-toolbar" });
    if (this.settings.enableComments) {
      const commentBtn = this.createToolbarButton("message-square-plus", "Add Comment", () => {
        this.addComment(activeView.editor, activeView);
      });
      this.authorToolbarEl.appendChild(commentBtn);
      const togglePanelBtn = this.createToolbarButton("message-square", "Toggle Comments Panel", () => {
        this.toggleCommentsPanel();
      });
      this.authorToolbarEl.appendChild(togglePanelBtn);
    }
    if (this.settings.enableComments && this.settings.enableTrackChanges) {
      this.authorToolbarEl.appendChild(createEl("div", { cls: "arcadia-author-separator" }));
    }
    if (this.settings.enableTrackChanges) {
      const trackBtn = this.createToolbarButton("git-compare", "Track Changes", () => {
        new import_obsidian.Notice("Track Changes feature coming in Phase 2");
      });
      trackBtn.addClass("is-disabled");
      this.authorToolbarEl.appendChild(trackBtn);
    }
    this.authorToolbarEl.appendChild(createEl("div", { cls: "arcadia-author-separator" }));
    const statsBtn = this.createToolbarButton("bar-chart-2", "Document Statistics", () => {
      this.showDocumentStatistics();
    });
    this.authorToolbarEl.appendChild(statsBtn);
    if (this.settings.enableTOC) {
      const tocBtn = this.createToolbarButton("list-tree", "Table of Contents", () => {
        new import_obsidian.Notice("Table of Contents feature coming in Phase 2");
      });
      tocBtn.addClass("is-disabled");
      this.authorToolbarEl.appendChild(tocBtn);
    }
    const arcadiaToolbar = editorEl.querySelector(".arcadia-toolbar");
    const cmScroller = editorEl.querySelector(".cm-scroller");
    if (arcadiaToolbar) {
      arcadiaToolbar.insertAdjacentElement("afterend", this.authorToolbarEl);
    } else if (cmScroller) {
      editorEl.insertBefore(this.authorToolbarEl, cmScroller);
    }
  }
  createToolbarButton(icon, tooltip, onClick) {
    const btn = createEl("button", {
      cls: "arcadia-author-button",
      attr: { "aria-label": tooltip, title: tooltip }
    });
    (0, import_obsidian.setIcon)(btn, icon);
    btn.addEventListener("click", (e) => {
      e.preventDefault();
      onClick();
    });
    return btn;
  }
  // ============================================================================
  // SIDECAR JSON ANNOTATIONS SYSTEM
  // ============================================================================
  getAnnotationsPath(file) {
    if (!file)
      return null;
    const basePath = file.path.replace(/\.md$/, "");
    return `${basePath}.arcadia.json`;
  }
  async loadAnnotationsForFile(file) {
    if (!file)
      return;
    const annotationsPath = this.getAnnotationsPath(file);
    if (!annotationsPath)
      return;
    try {
      const annotationsFile = this.app.vault.getAbstractFileByPath(annotationsPath);
      if (annotationsFile instanceof import_obsidian.TFile) {
        const content = await this.app.vault.read(annotationsFile);
        const annotations = JSON.parse(content);
        this.currentAnnotations.set(file.path, annotations);
      } else {
        this.currentAnnotations.set(file.path, {
          version: "1.0.0",
          comments: [],
          trackChanges: []
        });
      }
    } catch (error) {
      console.error("Error loading annotations:", error);
      this.currentAnnotations.set(file.path, {
        version: "1.0.0",
        comments: [],
        trackChanges: []
      });
    }
  }
  async saveAnnotationsForFile(file) {
    if (!file)
      return;
    const annotationsPath = this.getAnnotationsPath(file);
    if (!annotationsPath)
      return;
    const annotations = this.currentAnnotations.get(file.path);
    if (!annotations)
      return;
    try {
      const content = JSON.stringify(annotations, null, 2);
      const existingFile = this.app.vault.getAbstractFileByPath(annotationsPath);
      if (existingFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existingFile, content);
      } else {
        await this.app.vault.create(annotationsPath, content);
      }
    } catch (error) {
      console.error("Error saving annotations:", error);
      new import_obsidian.Notice("Failed to save annotations");
    }
  }
  // ============================================================================
  // COMMENTS SYSTEM
  // ============================================================================
  addComment(editor, view) {
    const selection = editor.getSelection();
    if (!selection) {
      new import_obsidian.Notice("Please select text to add a comment");
      return;
    }
    const file = view.file;
    if (!file)
      return;
    new AddCommentModal(this.app, selection, this.settings.defaultAuthor, async (commentText, author) => {
      const from = editor.getCursor("from");
      const to = editor.getCursor("to");
      const startOffset = editor.posToOffset(from);
      const endOffset = editor.posToOffset(to);
      const comment = {
        id: this.generateId(),
        text: commentText,
        author,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        resolved: false,
        startOffset,
        endOffset,
        replies: []
      };
      const annotations = this.currentAnnotations.get(file.path);
      if (annotations) {
        annotations.comments.push(comment);
        await this.saveAnnotationsForFile(file);
        new import_obsidian.Notice("Comment added");
        this.updateCommentsPanel();
      }
    }).open();
  }
  toggleCommentsPanel() {
    if (this.commentsPanelEl && this.commentsPanelEl.isShown()) {
      this.commentsPanelEl.hide();
    } else {
      this.showCommentsPanel();
    }
  }
  showCommentsPanel() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!(activeView == null ? void 0 : activeView.file)) {
      new import_obsidian.Notice("No active document");
      return;
    }
    if (!this.commentsPanelEl) {
      this.commentsPanelEl = createEl("div", { cls: "arcadia-comments-panel" });
      document.body.appendChild(this.commentsPanelEl);
    }
    this.updateCommentsPanel();
    this.commentsPanelEl.show();
  }
  updateCommentsPanel() {
    if (!this.commentsPanelEl)
      return;
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!(activeView == null ? void 0 : activeView.file))
      return;
    const annotations = this.currentAnnotations.get(activeView.file.path);
    if (!annotations)
      return;
    this.commentsPanelEl.empty();
    const header = this.commentsPanelEl.createEl("div", { cls: "arcadia-comments-header" });
    header.createEl("h3", { text: "Comments" });
    const closeBtn = header.createEl("button", { cls: "arcadia-comments-close" });
    (0, import_obsidian.setIcon)(closeBtn, "x");
    closeBtn.addEventListener("click", () => {
      var _a;
      return (_a = this.commentsPanelEl) == null ? void 0 : _a.hide();
    });
    const list = this.commentsPanelEl.createEl("div", { cls: "arcadia-comments-list" });
    const visibleComments = annotations.comments.filter(
      (c) => this.settings.showResolvedComments || !c.resolved
    );
    if (visibleComments.length === 0) {
      list.createEl("p", {
        text: 'No comments yet. Select text and click "Add Comment" to create one.',
        cls: "arcadia-comments-empty"
      });
    } else {
      visibleComments.forEach((comment) => {
        const commentEl = this.createCommentElement(comment, activeView.file);
        list.appendChild(commentEl);
      });
    }
  }
  createCommentElement(comment, file) {
    const el = createEl("div", { cls: "arcadia-comment" });
    if (comment.resolved) {
      el.addClass("is-resolved");
    }
    const headerEl = el.createEl("div", { cls: "arcadia-comment-header" });
    headerEl.createEl("span", { text: comment.author, cls: "arcadia-comment-author" });
    headerEl.createEl("span", {
      text: new Date(comment.createdAt).toLocaleDateString(),
      cls: "arcadia-comment-date"
    });
    el.createEl("p", { text: comment.text, cls: "arcadia-comment-text" });
    const actionsEl = el.createEl("div", { cls: "arcadia-comment-actions" });
    const resolveBtn = actionsEl.createEl("button", {
      text: comment.resolved ? "Unresolve" : "Resolve",
      cls: "arcadia-comment-action"
    });
    resolveBtn.addEventListener("click", async () => {
      comment.resolved = !comment.resolved;
      comment.updatedAt = new Date().toISOString();
      await this.saveAnnotationsForFile(file);
      this.updateCommentsPanel();
    });
    const deleteBtn = actionsEl.createEl("button", {
      text: "Delete",
      cls: "arcadia-comment-action arcadia-comment-delete"
    });
    deleteBtn.addEventListener("click", async () => {
      const annotations = this.currentAnnotations.get(file.path);
      if (annotations) {
        annotations.comments = annotations.comments.filter((c) => c.id !== comment.id);
        await this.saveAnnotationsForFile(file);
        this.updateCommentsPanel();
        new import_obsidian.Notice("Comment deleted");
      }
    });
    if (comment.replies.length > 0) {
      const repliesEl = el.createEl("div", { cls: "arcadia-comment-replies" });
      comment.replies.forEach((reply) => {
        const replyEl = repliesEl.createEl("div", { cls: "arcadia-comment-reply" });
        replyEl.createEl("span", { text: reply.author, cls: "arcadia-comment-author" });
        replyEl.createEl("p", { text: reply.text });
      });
    }
    const replyBtn = actionsEl.createEl("button", {
      text: "Reply",
      cls: "arcadia-comment-action"
    });
    replyBtn.addEventListener("click", () => {
      new AddReplyModal(this.app, this.settings.defaultAuthor, async (replyText, author) => {
        const reply = {
          id: this.generateId(),
          text: replyText,
          author,
          createdAt: new Date().toISOString()
        };
        comment.replies.push(reply);
        comment.updatedAt = new Date().toISOString();
        await this.saveAnnotationsForFile(file);
        this.updateCommentsPanel();
      }).open();
    });
    return el;
  }
  async resolveAllComments() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!(activeView == null ? void 0 : activeView.file)) {
      new import_obsidian.Notice("No active document");
      return;
    }
    const annotations = this.currentAnnotations.get(activeView.file.path);
    if (!annotations || annotations.comments.length === 0) {
      new import_obsidian.Notice("No comments to resolve");
      return;
    }
    annotations.comments.forEach((comment) => {
      comment.resolved = true;
      comment.updatedAt = new Date().toISOString();
    });
    await this.saveAnnotationsForFile(activeView.file);
    this.updateCommentsPanel();
    new import_obsidian.Notice("All comments resolved");
  }
  // ============================================================================
  // WORD COUNT SYSTEM
  // ============================================================================
  calculateWordCount(text) {
    const contentWithoutFrontmatter = text.replace(/^---[\s\S]*?---\n?/, "");
    const cleanText = contentWithoutFrontmatter.replace(/```[\s\S]*?```/g, "").replace(/`[^`]+`/g, "").replace(/!\[.*?\]\(.*?\)/g, "").replace(/\[([^\]]+)\]\(.*?\)/g, "$1").replace(/[#*_~`>]/g, "").replace(/\n/g, " ").trim();
    const words = cleanText.split(/\s+/).filter((word) => word.length > 0);
    const sentences = cleanText.split(/[.!?]+/).filter((s) => s.trim().length > 0);
    const paragraphs = contentWithoutFrontmatter.split(/\n\s*\n/).filter((p) => p.trim().length > 0);
    return {
      words: words.length,
      characters: text.length,
      charactersNoSpaces: text.replace(/\s/g, "").length,
      sentences: sentences.length,
      paragraphs: paragraphs.length,
      readingTime: Math.ceil(words.length / this.settings.wordsPerMinute)
    };
  }
  updateWordCount(editor) {
    if (!this.settings.enableWordCount)
      return;
    const text = editor.getValue();
    const stats = this.calculateWordCount(text);
    if (this.statusBarItem) {
      const parts = [];
      if (this.settings.showWordCount) {
        parts.push(`${stats.words} words`);
      }
      if (this.settings.showCharacterCount) {
        parts.push(`${stats.characters} chars`);
      }
      if (this.settings.showReadingTime) {
        parts.push(`${stats.readingTime} min read`);
      }
      this.statusBarItem.setText(parts.join(" | "));
    }
  }
  showDocumentStatistics() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!(activeView == null ? void 0 : activeView.editor)) {
      new import_obsidian.Notice("No active document");
      return;
    }
    const text = activeView.editor.getValue();
    const stats = this.calculateWordCount(text);
    new DocumentStatisticsModal(this.app, stats).open();
  }
  // ============================================================================
  // EXPORT FUNCTIONS
  // ============================================================================
  async exportCleanMarkdown() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!(activeView == null ? void 0 : activeView.file)) {
      new import_obsidian.Notice("No active document");
      return;
    }
    const content = activeView.editor.getValue();
    await navigator.clipboard.writeText(content);
    new import_obsidian.Notice("Clean markdown copied to clipboard");
  }
  // ============================================================================
  // UTILITIES
  // ============================================================================
  generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
  }
};
var AddCommentModal = class extends import_obsidian.Modal {
  constructor(app, selection, defaultAuthor, onSubmit) {
    super(app);
    this.selection = selection;
    this.defaultAuthor = defaultAuthor;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("arcadia-modal");
    contentEl.createEl("h2", { text: "Add Comment" });
    const selectionEl = contentEl.createEl("div", { cls: "arcadia-modal-selection" });
    selectionEl.createEl("label", { text: "Selected text:" });
    selectionEl.createEl("blockquote", { text: this.selection });
    const authorSetting = new import_obsidian.Setting(contentEl).setName("Author").addText((text) => text.setValue(this.defaultAuthor).setPlaceholder("Your name"));
    let commentText = "";
    const commentSetting = new import_obsidian.Setting(contentEl).setName("Comment").addTextArea((textarea) => {
      textarea.setPlaceholder("Enter your comment...");
      textarea.inputEl.rows = 4;
      textarea.onChange((value) => commentText = value);
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close())).addButton((btn) => btn.setButtonText("Add Comment").setCta().onClick(() => {
      if (commentText.trim()) {
        const authorInput = authorSetting.controlEl.querySelector("input");
        const author = (authorInput == null ? void 0 : authorInput.value) || this.defaultAuthor;
        this.onSubmit(commentText.trim(), author);
        this.close();
      } else {
        new import_obsidian.Notice("Please enter a comment");
      }
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AddReplyModal = class extends import_obsidian.Modal {
  constructor(app, defaultAuthor, onSubmit) {
    super(app);
    this.defaultAuthor = defaultAuthor;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("arcadia-modal");
    contentEl.createEl("h2", { text: "Add Reply" });
    const authorSetting = new import_obsidian.Setting(contentEl).setName("Author").addText((text) => text.setValue(this.defaultAuthor).setPlaceholder("Your name"));
    let replyText = "";
    new import_obsidian.Setting(contentEl).setName("Reply").addTextArea((textarea) => {
      textarea.setPlaceholder("Enter your reply...");
      textarea.inputEl.rows = 3;
      textarea.onChange((value) => replyText = value);
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close())).addButton((btn) => btn.setButtonText("Add Reply").setCta().onClick(() => {
      if (replyText.trim()) {
        const authorInput = authorSetting.controlEl.querySelector("input");
        const author = (authorInput == null ? void 0 : authorInput.value) || this.defaultAuthor;
        this.onSubmit(replyText.trim(), author);
        this.close();
      } else {
        new import_obsidian.Notice("Please enter a reply");
      }
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var DocumentStatisticsModal = class extends import_obsidian.Modal {
  constructor(app, stats) {
    super(app);
    this.stats = stats;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("arcadia-modal");
    contentEl.createEl("h2", { text: "Document Statistics" });
    const statsGrid = contentEl.createEl("div", { cls: "arcadia-stats-grid" });
    this.createStatItem(statsGrid, "Words", this.stats.words.toLocaleString());
    this.createStatItem(statsGrid, "Characters", this.stats.characters.toLocaleString());
    this.createStatItem(statsGrid, "Characters (no spaces)", this.stats.charactersNoSpaces.toLocaleString());
    this.createStatItem(statsGrid, "Sentences", this.stats.sentences.toLocaleString());
    this.createStatItem(statsGrid, "Paragraphs", this.stats.paragraphs.toLocaleString());
    this.createStatItem(statsGrid, "Reading Time", `${this.stats.readingTime} min`);
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Close").setCta().onClick(() => this.close()));
  }
  createStatItem(container, label, value) {
    const item = container.createEl("div", { cls: "arcadia-stat-item" });
    item.createEl("div", { text: value, cls: "arcadia-stat-value" });
    item.createEl("div", { text: label, cls: "arcadia-stat-label" });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ArcadiaAuthorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Arcadia Author Settings" });
    containerEl.createEl("h3", { text: "Features" });
    new import_obsidian.Setting(containerEl).setName("Enable Comments").setDesc("Allow adding inline comments and annotations to documents").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableComments).onChange(async (value) => {
      this.plugin.settings.enableComments = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Track Changes").setDesc("Track insertions and deletions (Phase 2 feature)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableTrackChanges).setDisabled(true).onChange(async (value) => {
      this.plugin.settings.enableTrackChanges = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Word Count").setDesc("Show word count and reading statistics").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableWordCount).onChange(async (value) => {
      this.plugin.settings.enableWordCount = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Auto-Numbering").setDesc("Automatically number headings (Phase 2 feature)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableAutoNumbering).setDisabled(true).onChange(async (value) => {
      this.plugin.settings.enableAutoNumbering = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Table of Contents").setDesc("Generate table of contents (Phase 2 feature)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableTOC).setDisabled(true).onChange(async (value) => {
      this.plugin.settings.enableTOC = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Comments" });
    new import_obsidian.Setting(containerEl).setName("Default Author").setDesc("Your name for comments").addText((text) => text.setValue(this.plugin.settings.defaultAuthor).setPlaceholder("Author").onChange(async (value) => {
      this.plugin.settings.defaultAuthor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Resolved Comments").setDesc("Display comments that have been marked as resolved").addToggle((toggle) => toggle.setValue(this.plugin.settings.showResolvedComments).onChange(async (value) => {
      this.plugin.settings.showResolvedComments = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Word Count" });
    new import_obsidian.Setting(containerEl).setName("Show Word Count").addToggle((toggle) => toggle.setValue(this.plugin.settings.showWordCount).onChange(async (value) => {
      this.plugin.settings.showWordCount = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Character Count").addToggle((toggle) => toggle.setValue(this.plugin.settings.showCharacterCount).onChange(async (value) => {
      this.plugin.settings.showCharacterCount = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Reading Time").addToggle((toggle) => toggle.setValue(this.plugin.settings.showReadingTime).onChange(async (value) => {
      this.plugin.settings.showReadingTime = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Words Per Minute").setDesc("Average reading speed for time estimates").addSlider((slider) => slider.setLimits(100, 400, 25).setValue(this.plugin.settings.wordsPerMinute).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.wordsPerMinute = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Word Count Position").setDesc("Where to display the word count").addDropdown((dropdown) => dropdown.addOption("statusbar", "Status Bar").addOption("toolbar", "Author Toolbar").setValue(this.plugin.settings.wordCountPosition).onChange(async (value) => {
      this.plugin.settings.wordCountPosition = value;
      await this.plugin.saveSettings();
    }));
  }
};
